# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9c9758fd74f7f8ff476330870cea94f3d9669c2f179dd92a5b2b6b07d4cf7170b8d18b2b877afdac98d5b68ef9621a55985ad0f7f933b5f77217518f12fed43

test:
  secret_key_base: 4b9d2286e022e1daae5dcd08a6562a527f522883222ec83d358542446c0e10b588b322d5ee8939f6b3e767815d0ace8bcac57562d10a63b5273aae518fa296b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
